import './globals.css';
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/app/_components/sidebar-components/sidebar.js"

import { SidebarContextProvider } from './_components/sidebar-components/sidebar.js'

import { SetDisplayVars } from './_utils/displayinfo.js';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import HomePageContainer from './_components/homepagecontainer'

export default function RootLayout({ children,
  chatArea,
  sidebar
}) {
  return (
    <html lang="en" className='m-0 w-full h-full '>

      <body className='m-0 w-full h-full flex flex-row justify-center items-center'>

        <SidebarContextProvider >


          <main className='box-border p-0 m-0 h-full w-full flex justify-center items-center shrink '>

            <div className="w-full h-full box-border p-0 m-0 border-0 flex justify-center items-center  bg-background text-foreground">
              <HomePageContainer>

                <div className="h-full shrink-0 flex flex-col justify-center items-center">
                  {sidebar}
                </div>
                <div className="flex-1 shrink w-full h-full ">{chatArea}
                </div>

              </HomePageContainer>
            </div>

          </main>

        </SidebarContextProvider>
      </body>
    </html >
  )
}
