import './globals.css';
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/app/_components/sidebar-components/sidebar.js"

import { SidebarContextProvider } from './_components/sidebar-components/sidebar.js'

import { SetDisplayVars } from './_utils/displayinfo.js';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='m-0 w-full h-full '>

      <body className='m-0 w-full h-full flex flex-row justify-center items-center'>

        <SidebarContextProvider >


          <main className='box-border p-0 m-0 h-full w-full flex justify-center items-center shrink '>
            {children}
          </main>

        </SidebarContextProvider>
      </body>
    </html >
  )
}
